"""POST /api/analyze — runs the agentic code-analysis loop on the cleaned dataset.

Flow:
  1. Load the original CSV.
  2. Apply the deterministic cleaner (so the agent starts from a normalized frame).
  3. Persist cleaned.csv to disk.
  4. Spawn the code agent: it writes its own pandas/scipy/matplotlib code, executes
     it in a per-session subprocess sandbox, iterates until it has substantive
     statistical results + charts, and returns a CodeAnalysisResult.
  5. Stream each completed code step as a `code_step` SSE event, then emit a final
     `result` event with the full payload so the UI can show steps as they arrive.

Chart files live under {settings.upload_dir}/{session_id}/charts/ and are served
by GET /api/charts/{session_id}/{filename} below.
"""

from pathlib import Path

import pandas as pd
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from config import settings
from models.schemas import AnalyzeRequest
from models import session as session_store
from services.cleaner import clean_dataframe
from services.agent import run_code_analysis
from services.analyzer import build_chart_specs, compute_summary_stats
from utils.file_utils import get_cleaned_path
from .streaming import stream_agent_events, sse_response

router = APIRouter()


@router.post("/analyze")
async def run_analysis(req: AnalyzeRequest):
    try:
        sess = session_store.get_session(req.session_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Session not found.")

    if not sess.profile:
        raise HTTPException(status_code=400, detail="Run /profile before /analyze.")

    def run(emit):
        try:
            df = pd.read_csv(sess.original_path)
        except Exception as e:
            return {"ok": False, "error": f"Could not read dataset: {e}"}

        cleaned_df, cleaning_steps = clean_dataframe(df, sess.profile)
        cleaned_path = get_cleaned_path(req.session_id)
        cleaned_df.to_csv(cleaned_path, index=False)

        chart_specs = build_chart_specs(cleaned_df, sess.profile)
        stats = compute_summary_stats(cleaned_df)

        work_dir = Path(settings.upload_dir) / req.session_id / "charts"
        work_dir.mkdir(parents=True, exist_ok=True)

        question = (req.question or sess.research_question or "").strip()

        result, code_steps, _events = run_code_analysis(
            question=question,
            csv_path=str(cleaned_path),
            work_dir=str(work_dir),
            profile=sess.profile,
            max_steps=12,
            on_event=emit,
        )

        payload = {
            "session_id": req.session_id,
            "research_question": question or None,
            "cleaning_steps": cleaning_steps,
            "steps": code_steps,
            "summary": result.summary if result else "",
            "findings": result.findings if result else "Agent did not return a final report.",
            "limitations": result.limitations if result else "",
            "follow_up": result.follow_up if result else "",
            "charts": chart_specs,
            "stats": stats,
        }
        session_store.update_session(
            req.session_id,
            analysis_result=payload,
            cleaned_path=str(cleaned_path),
        )
        return payload

    return sse_response(stream_agent_events(run))


@router.get("/charts/{session_id}/{filename}")
def serve_chart(session_id: str, filename: str):
    """Serve a chart PNG generated by the code agent for a given session."""
    if "/" in filename or ".." in filename or "\\" in filename:
        raise HTTPException(status_code=404, detail="Not found")
    path = Path(settings.upload_dir) / session_id / "charts" / filename
    if not path.exists() or not path.is_file():
        raise HTTPException(status_code=404, detail="Chart not found")
    return FileResponse(path, media_type="image/png")
