"""Generate a stand-alone Python script from a session's code-agent run.

We don't template anything. We just stitch together the actual code blocks the
agent wrote and successfully ran (stored on session.analysis_result["steps"]),
prefix them with the same preamble the sandbox uses (so `df`, scipy, plt are
in scope), and add section comments showing the agent's rationale + a snippet
of the printed output it produced. Running the script outside the app produces
the same numbers and the same chart PNGs as the in-app run.
"""

from __future__ import annotations

from typing import Any

from models.session import SessionData
from services.sandbox import PREAMBLE


def _comment_block(text: str, prefix: str = "# ") -> str:
    if not text:
        return ""
    return "\n".join(prefix + line for line in text.splitlines())


def build_script(session: SessionData) -> str:
    analysis = session.analysis_result or {}
    steps: list[dict[str, Any]] = list(analysis.get("steps") or [])
    question = (analysis.get("research_question") or session.research_question or "").strip()
    csv_path = session.cleaned_path or session.original_path or "<dataset>.csv"

    # Filter to successful steps. Failed code blocks aren't worth shipping.
    good_steps = [s for s in steps if s.get("ok", True) and s.get("code")]

    parts: list[str] = []
    parts.append('"""Reproduces the HealthLab Agent analysis end-to-end.')
    parts.append("")
    if question:
        parts.append(f"Research question: {question}")
        parts.append("")
    parts.append(f"Source dataset: {session.filename}")
    parts.append("Generated by HealthLab Agent — modify freely.")
    parts.append('"""')
    parts.append("")
    parts.append(f'import os')
    parts.append(f'os.environ.setdefault("HEALTHLAB_CSV", {csv_path!r})')
    parts.append(PREAMBLE.strip())
    parts.append("")

    if not good_steps:
        parts.append("# No successful agent code blocks were recorded for this session.")
        parts.append("print('Nothing to run — re-run the analysis to populate this script.')")
        return "\n".join(parts) + "\n"

    for i, step in enumerate(good_steps, 1):
        rationale = (step.get("rationale") or "").strip()
        code = step.get("code", "").rstrip()
        stdout = (step.get("stdout") or "").strip()
        charts = step.get("charts") or []

        parts.append("")
        parts.append("# " + ("=" * 70))
        parts.append(f"# Step {i}" + (f": {rationale}" if rationale else ""))
        parts.append("# " + ("=" * 70))
        parts.append(code)
        if stdout:
            preview = "\n".join(stdout.splitlines()[:8])
            parts.append("")
            parts.append("# --- stdout from this step (preview, first 8 lines) ---")
            parts.append(_comment_block(preview))
        if charts:
            parts.append(f"# Charts saved: {', '.join(charts)}")

    parts.append("")
    parts.append("print('\\nDone — see printed output above and any chart_*.png files in the working directory.')")
    return "\n".join(parts) + "\n"
