from datetime import datetime
from typing import Any


def _stats_table(stats: list[dict[str, Any]]) -> str:
    if not stats:
        return "_No numeric columns found._"
    header = "| Column | Count | Mean | Median | Std | Min | Max |"
    sep = "|--------|-------|------|--------|-----|-----|-----|"
    rows = [
        f"| {s['column']} | {s['count']} | {s['mean']} | {s['median']} | {s['std']} | {s['min']} | {s['max']} |"
        for s in stats
    ]
    return "\n".join([header, sep] + rows)


def _column_table(columns: list[dict[str, Any]]) -> str:
    header = "| Column | Type | Missing | Missing% | Unique |"
    sep = "|--------|------|---------|----------|--------|"
    rows = [
        f"| {c['name']} | {c['dtype_inferred']} | {c['missing_count']} | {c['missing_pct']}% | {c['unique_count']} |"
        for c in columns
    ]
    return "\n".join([header, sep] + rows)


def build_markdown_memo(
    filename: str,
    profile: dict[str, Any],
    cleaning_steps: list[str],
    stats: list[dict[str, Any]],
    chart_specs: list[dict[str, Any]],
    findings: str,
    limitations: str,
    follow_up: str,
    generated_at: str | None = None,
) -> str:
    if generated_at is None:
        generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    chart_list = "\n".join(
        f"- **{c['title']}** ({c['chart_type'].title()} chart)" for c in chart_specs
    )

    outlier_notes = []
    for col in profile.get("columns", []):
        if col.get("outliers"):
            n = len(col["outliers"])
            outlier_notes.append(f"- `{col['name']}`: {n} outlier(s) detected (IQR method)")
    outlier_section = "\n".join(outlier_notes) if outlier_notes else "_No outliers detected._"

    cleaning_section = "\n".join(f"- {s}" for s in cleaning_steps) if cleaning_steps else "_No cleaning steps required._"

    memo = f"""# HealthLab Agent — Research Memo

**Dataset:** {filename}
**Generated:** {generated_at}
**Shape:** {profile['row_count']} rows × {profile['col_count']} columns

---

## 1. Dataset Overview

{_column_table(profile.get('columns', []))}

**Duplicate rows detected:** {profile.get('duplicate_rows', 0)}

---

## 2. Data Quality Notes

**Missing data by column:**
{chr(10).join(f"- `{c['name']}`: {c['missing_pct']}% missing ({c['missing_count']} values)" for c in profile.get('columns', []) if c['missing_count'] > 0) or "_No missing data detected._"}

**Outliers:**
{outlier_section}

---

## 3. Cleaning Steps Applied

{cleaning_section}

---

## 4. Summary Statistics

{_stats_table(stats)}

---

## 5. Charts Generated

{chart_list or "_No charts generated._"}

---

## 6. Key Findings

{findings}

---

## 7. Limitations

{limitations}

---

## 8. Suggested Follow-Up Analyses

{follow_up}

---

## 9. Methods Note

This analysis was performed by HealthLab Agent using automated data profiling (IQR-based outlier detection, median imputation for missing numeric values) and exploratory statistical analysis. All findings are descriptive and observational. No causal claims should be drawn without experimental or quasi-experimental study designs.

---

_Generated by [HealthLab Agent](https://healthlab-agent.app) — an autonomous public health data analysis assistant._
"""
    return memo
